Acme\BasicCmsBundle\Document\Page:
    url_schema: /page/{title}
    token_providers:
        title: [content_method, { method: getTitle } ]

Acme\BasicCmsBundle\Document\Post:
    url_schema: /post/{date}/{title}
    token_providers:
        date: [content_datetime, { method: getDate } ]
        title: [content_method, { method: getTitle }]
